package com.controlecci.view;

import javax.swing.JOptionPane;

/**
 *
 * @author Instrutores
 */
public class DialogoRegistro extends javax.swing.JDialog {

    /**
     * Creates new form DialogoRegistro
     *
     * @param parent
     * @param modal
     */
    public DialogoRegistro(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jlRegistro = new javax.swing.JLabel();
        jlNovoRegistro = new javax.swing.JLabel();
        jlConsulta = new javax.swing.JLabel();
        jlCadastroCurso = new javax.swing.JLabel();
        jlCadastroAluno = new javax.swing.JLabel();
        jlTelaPrincipal = new javax.swing.JLabel();
        jlCadastroAluno2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 112, 192));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("O HORÁRIO DO ALUNO FOI REGISTRADO COM SUCESSO!");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("O QUE DESEJA FAZER AGORA?");

        jlRegistro.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jlRegistro.setForeground(new java.awt.Color(255, 255, 255));
        jlRegistro.setText("1- INSERIR UM NOVO REGISTRO PARA O MESMO ALUNO (F1)");
        jlRegistro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlRegistroMouseClicked(evt);
            }
        });

        jlNovoRegistro.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jlNovoRegistro.setForeground(new java.awt.Color(255, 255, 255));
        jlNovoRegistro.setText("2 - INSERIR UM NOVO REGISTRO PARA OUTRO ALUNO (F2)");
        jlNovoRegistro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlNovoRegistroMouseClicked(evt);
            }
        });

        jlConsulta.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jlConsulta.setForeground(new java.awt.Color(255, 255, 255));
        jlConsulta.setText("3 - CONSULTAR O REGISTRO DE UM ALUNO (F3)");
        jlConsulta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlConsultaMouseClicked(evt);
            }
        });

        jlCadastroCurso.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jlCadastroCurso.setForeground(new java.awt.Color(255, 255, 255));
        jlCadastroCurso.setText("4 - CADASTRAR NO SISTEMA UM NOVO CURSO (F4)");
        jlCadastroCurso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlCadastroCursoMouseClicked(evt);
            }
        });

        jlCadastroAluno.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jlCadastroAluno.setForeground(new java.awt.Color(255, 255, 255));
        jlCadastroAluno.setText("5 - CADASTRAR NO SISTEMA UM NOVO ALUNO (F5)");
        jlCadastroAluno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlCadastroAlunoMouseClicked(evt);
            }
        });

        jlTelaPrincipal.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jlTelaPrincipal.setForeground(new java.awt.Color(255, 255, 255));
        jlTelaPrincipal.setText("6 - VOLTAR A TELA PRINCIPAL DO SISTEMA (F6)");
        jlTelaPrincipal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlTelaPrincipalMouseClicked(evt);
            }
        });

        jlCadastroAluno2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jlCadastroAluno2.setForeground(new java.awt.Color(255, 255, 255));
        jlCadastroAluno2.setText("7 - ENCERRAR SISTEMA (F7)");
        jlCadastroAluno2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlCadastroAluno2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlRegistro)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(jLabel2))
                    .addComponent(jlNovoRegistro)
                    .addComponent(jlConsulta)
                    .addComponent(jlCadastroCurso)
                    .addComponent(jlCadastroAluno)
                    .addComponent(jlTelaPrincipal)
                    .addComponent(jlCadastroAluno2))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jlRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jlNovoRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jlConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jlCadastroCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jlCadastroAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jlTelaPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jlCadastroAluno2, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenu1.setText("FUNÇÕES");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        jMenuItem1.setText("REGISTRO PARA MESMO ALUNO");
        jMenu1.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, 0));
        jMenuItem2.setText("REGISTRO PARA NOVO ALUNO");
        jMenu1.add(jMenuItem2);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F3, 0));
        jMenuItem3.setText("CONSULTAR REGISTRO DE ALUNO");
        jMenu1.add(jMenuItem3);

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, 0));
        jMenuItem4.setText("CADASTRAR NOVO CURSO");
        jMenu1.add(jMenuItem4);

        jMenuItem5.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F5, 0));
        jMenuItem5.setText("CADASTRAR NOVO ALUNO");
        jMenu1.add(jMenuItem5);

        jMenuItem6.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F6, 0));
        jMenuItem6.setText("VOLTAR A TELA PRINCIPAL");
        jMenu1.add(jMenuItem6);

        jMenuItem7.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F7, 0));
        jMenuItem7.setText("ENECERRAR SISTEMA");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem7);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jlRegistroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlRegistroMouseClicked
        this.dispose();
    }//GEN-LAST:event_jlRegistroMouseClicked

    private void jlNovoRegistroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlNovoRegistroMouseClicked
        this.dispose();
        new FrmAlunos().setVisible(true);
    }//GEN-LAST:event_jlNovoRegistroMouseClicked

    private void jlConsultaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlConsultaMouseClicked
        this.dispose();
        new ConsultaAlunos().setVisible(true);

    }//GEN-LAST:event_jlConsultaMouseClicked

    private void jlCadastroCursoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlCadastroCursoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jlCadastroCursoMouseClicked

    private void jlCadastroAlunoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlCadastroAlunoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jlCadastroAlunoMouseClicked

    private void jlTelaPrincipalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlTelaPrincipalMouseClicked
        this.dispose();
        new TelaPrincipal().setVisible(true);
    }//GEN-LAST:event_jlTelaPrincipalMouseClicked

    private void jlCadastroAluno2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlCadastroAluno2MouseClicked
        JOptionPane.showMessageDialog(this, "O SISTEMA SERÁ ENCERRADO!", "ATENÇÃO", JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_jlCadastroAluno2MouseClicked

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DialogoRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DialogoRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DialogoRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DialogoRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(() -> {
            DialogoRegistro dialog = new DialogoRegistro(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JLabel jlCadastroAluno;
    private javax.swing.JLabel jlCadastroAluno2;
    private javax.swing.JLabel jlCadastroCurso;
    private javax.swing.JLabel jlConsulta;
    private javax.swing.JLabel jlNovoRegistro;
    private javax.swing.JLabel jlRegistro;
    private javax.swing.JLabel jlTelaPrincipal;
    // End of variables declaration//GEN-END:variables
}
