package com.controlecci.view.SCCI;

import com.controlecci.controller.AlunoController;
import com.controlecci.controller.CursoController;
import com.controlecci.model.AlunoModel;
import com.controlecci.util.ColorirLinhaStatus;
import com.controlecci.util.GetDateUtil;
import com.controlecci.util.LocalUtil;
import com.controlecci.util.LogCatUtil;
import com.controlecci.util.TemplateAlerts;
import com.controlecci.view.utils.MensagemConfirmação;
import com.controlecci.view.utils.SelecionaAluno;
import com.controlecci.view.utils.TelaCarregamento;
import com.mxrck.autocompleter.AutoCompleter;
import com.mxrck.autocompleter.TextAutoCompleter;
import java.awt.Dimension;
import java.awt.HeadlessException;
import java.text.ParseException;
import java.util.ArrayList;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author joseluiz
 */
public class AlunoView extends javax.swing.JInternalFrame {

    AlunoModel alunoModel = new AlunoModel();
    AlunoController alunoController = new AlunoController();
    CursoController cursoController = new CursoController();
    public ArrayList lista = new ArrayList<>();
    public ArrayList<AlunoModel> listaAlunoModels = new ArrayList<>();

    MensagemConfirmação mensagemConfirmação = new MensagemConfirmação(null, true);
    TelaCarregamento telaCarregamento = new TelaCarregamento(null, true);

    GetDateUtil getDateUtil = new GetDateUtil();
    TemplateAlerts templateAlerts = new TemplateAlerts();

    private AutoCompleter ac, ac2;

    /**
     * Creates new form AlunoView
     */
    public AlunoView() {
        initComponents();
        setarEstado();
        limparCamposSalvar();
        limparCamposAlterar();
        autoCompletarCurso();
        autoCompletarAluno();
        habilitaDesabilitaCamposSalvar(false);
        habilitarCamposAlterar(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jlCliente = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jtfMatricula = new javax.swing.JTextField();
        jtfNome = new javax.swing.JTextField();
        jtfCpf = new javax.swing.JFormattedTextField();
        jtfRg = new javax.swing.JTextField();
        jtfEndereco = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jtfComplemento = new javax.swing.JTextField();
        jtfNumero = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jtfBairro = new javax.swing.JTextField();
        jtfCep = new javax.swing.JFormattedTextField();
        jtfCidade = new javax.swing.JTextField();
        jcbUf = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jtfTelefone = new javax.swing.JFormattedTextField();
        jtfCelular = new javax.swing.JFormattedTextField();
        jtfEmail = new javax.swing.JTextField();
        jtfCurso = new javax.swing.JTextField();
        jlCargaHoraria = new javax.swing.JLabel();
        jbCancelar = new javax.swing.JButton();
        jbNovo = new javax.swing.JButton();
        jbSalvar = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jtfData = new javax.swing.JFormattedTextField();
        jtfDataMatricula = new javax.swing.JFormattedTextField();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jtfTelefoneAlterar = new javax.swing.JFormattedTextField();
        jtfMatriculaAlterar = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtfNomeAlterar = new javax.swing.JTextField();
        jtfNumeroAlterar = new javax.swing.JTextField();
        jtfComplementoAlterar = new javax.swing.JTextField();
        jtfCpfAlterar = new javax.swing.JFormattedTextField();
        jtfEnderecoAlterar = new javax.swing.JTextField();
        jcbUfAlterar = new javax.swing.JComboBox<>();
        jLabel27 = new javax.swing.JLabel();
        jtfRgAlterar = new javax.swing.JTextField();
        jtfCidadeAlterar = new javax.swing.JTextField();
        jlCliente1 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jtfBairroAlterar = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jtfCepAlterar = new javax.swing.JFormattedTextField();
        jtfEmailAlterar = new javax.swing.JTextField();
        jbCancelarAlterar = new javax.swing.JButton();
        jLabel29 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jbAlterar = new javax.swing.JButton();
        jlCargaHorariaAlterar = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jtfCelularAlterar = new javax.swing.JFormattedTextField();
        jtfCursoAlterar = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        jtfPesquisa = new javax.swing.JTextField();
        jbPesquisa = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jcbStatus = new javax.swing.JComboBox<>();
        jLabel26 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jtfDataMatriculaAlterar = new javax.swing.JFormattedTextField();
        jLabel38 = new javax.swing.JLabel();
        jtfDataAlterar = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtAlunos = new javax.swing.JTable();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jbAtualizarTabela = new javax.swing.JButton();
        jLabel39 = new javax.swing.JLabel();
        jlQtde = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setTitle("SCCI - ALUNO");

        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.BOTTOM);

        jPanel4.setBackground(new java.awt.Color(28, 89, 124));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("MATRICULA");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("NOME");

        jlCliente.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jlCliente.setForeground(new java.awt.Color(255, 255, 255));
        jlCliente.setText("CPF");

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("RG");

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("DATA NASCIMENTO");

        jtfMatricula.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jtfNome.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        try {
            jtfCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jtfCpf.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jtfRg.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jtfEndereco.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("ENDEREÇO");

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("N°");

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("COMPLEMENTO");

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("BAIRRO");

        jtfComplemento.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jtfNumero.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("CIDADE");

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("UF");

        jLabel14.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("CEP");

        jtfBairro.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        try {
            jtfCep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jtfCep.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jtfCidade.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jcbUf.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jcbUf.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PE" }));

        jLabel15.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("TELEFONE");

        jLabel16.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("CELULAR");

        jLabel17.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("EMAIL");

        jLabel18.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("CURSO");

        try {
            jtfTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(81) ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jtfTelefone.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jtfTelefone.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        try {
            jtfCelular.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(81) 9 ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jtfCelular.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jtfCelular.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jtfEmail.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jtfCurso.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jtfCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfCursoActionPerformed(evt);
            }
        });

        jlCargaHoraria.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jlCargaHoraria.setForeground(new java.awt.Color(255, 255, 255));
        jlCargaHoraria.setText("HH:MM:SS");

        jbCancelar.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jbCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/controlecci/image/actions/cancelar.png"))); // NOI18N
        jbCancelar.setText("CANCELAR");
        jbCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelarActionPerformed(evt);
            }
        });

        jbNovo.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jbNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/controlecci/image/actions/add.png"))); // NOI18N
        jbNovo.setText("NOVO");
        jbNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNovoActionPerformed(evt);
            }
        });

        jbSalvar.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jbSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/controlecci/image/actions/salvar.png"))); // NOI18N
        jbSalvar.setText("SALVAR");
        jbSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalvarActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("CARGA HORÁRIA");

        jLabel19.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("DATA DA MATRICULA");

        try {
            jtfData.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##-##-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jtfData.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtfData.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        try {
            jtfDataMatricula.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##-##-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jtfDataMatricula.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtfDataMatricula.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addComponent(jtfEndereco)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtfNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jtfComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addComponent(jtfCidade)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13)
                                    .addComponent(jcbUf, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGap(354, 577, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jtfMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfNome)
                        .addContainerGap())
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jtfCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtfRg)
                                .addGap(159, 159, 159))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addComponent(jtfCep, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jtfBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(12, 12, 12))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(jtfTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(jtfCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addGap(172, 172, 172))
                            .addComponent(jtfEmail))
                        .addGap(12, 12, 12))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jbCancelar)
                        .addGap(116, 116, 116)
                        .addComponent(jbNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jtfCurso, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel19)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jtfDataMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jlCargaHoraria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(97, 97, 97)
                                .addComponent(jLabel2))
                            .addComponent(jLabel12))
                        .addGap(92, 389, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jtfData, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                .addComponent(jlCliente)
                                .addGap(157, 157, 157)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5)))
                        .addGap(23, 23, 23))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlCliente)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(jLabel5)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfRg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtfCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbUf, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlCargaHoraria))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jtfDataMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbNovo)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jbSalvar)
                        .addComponent(jbCancelar)))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("NOVO ALUNO", jPanel1);

        jPanel5.setBackground(new java.awt.Color(28, 89, 124));

        try {
            jtfTelefoneAlterar.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(81) ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jtfTelefoneAlterar.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jtfTelefoneAlterar.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jtfMatriculaAlterar.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("MATRICULA");

        jtfNomeAlterar.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jtfNumeroAlterar.setEditable(false);
        jtfNumeroAlterar.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jtfComplementoAlterar.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        try {
            jtfCpfAlterar.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jtfCpfAlterar.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jtfEnderecoAlterar.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jcbUfAlterar.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jcbUfAlterar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PE" }));

        jLabel27.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("CIDADE");

        jtfRgAlterar.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jtfCidadeAlterar.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jlCliente1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jlCliente1.setForeground(new java.awt.Color(255, 255, 255));
        jlCliente1.setText("CPF");

        jLabel24.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("COMPLEMENTO");

        jLabel22.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("ENDEREÇO");

        jtfBairroAlterar.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jLabel23.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("N°");

        try {
            jtfCepAlterar.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jtfCepAlterar.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jtfEmailAlterar.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jbCancelarAlterar.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jbCancelarAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/controlecci/image/actions/cancelar.png"))); // NOI18N
        jbCancelarAlterar.setText("CANCELAR");
        jbCancelarAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelarAlterarActionPerformed(evt);
            }
        });

        jLabel29.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("CEP");

        jLabel31.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText("CELULAR");

        jLabel20.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("RG");

        jLabel33.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setText("CURSO");

        jLabel32.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("EMAIL");

        jLabel30.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("TELEFONE");

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("NOME");

        jLabel25.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("BAIRRO");

        jbAlterar.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jbAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/controlecci/image/actions/salvar.png"))); // NOI18N
        jbAlterar.setText("ALTERAR");
        jbAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAlterarActionPerformed(evt);
            }
        });

        jlCargaHorariaAlterar.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jlCargaHorariaAlterar.setForeground(new java.awt.Color(255, 255, 255));
        jlCargaHorariaAlterar.setText("HH:MM:SS");

        jLabel21.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("DATA NASCIMENTO");

        jLabel28.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("UF");

        try {
            jtfCelularAlterar.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(81) 9 ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jtfCelularAlterar.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jtfCelularAlterar.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jtfCursoAlterar.setEditable(false);
        jtfCursoAlterar.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jtfCursoAlterar.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtfCursoAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfCursoAlterarActionPerformed(evt);
            }
        });

        jLabel35.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(255, 255, 255));
        jLabel35.setText("ALUNO");

        jtfPesquisa.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jtfPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfPesquisaActionPerformed(evt);
            }
        });

        jbPesquisa.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jbPesquisa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/controlecci/image/actions/pesquisar.png"))); // NOI18N
        jbPesquisa.setText("PESQUISAR");
        jbPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPesquisaActionPerformed(evt);
            }
        });

        jcbStatus.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jcbStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ATIVO", "SUSPENSO", "CONCLUÍDO" }));

        jLabel26.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("STATUS ALUNO");

        jLabel34.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setText("CARGA HORÁRIA");

        jtfDataMatriculaAlterar.setEditable(false);
        try {
            jtfDataMatriculaAlterar.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jtfDataMatriculaAlterar.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtfDataMatriculaAlterar.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jLabel38.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(255, 255, 255));
        jLabel38.setText("MATRÍCULA");

        jtfDataAlterar.setEditable(false);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel29)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel25)
                        .addGap(366, 366, 366))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jtfCpfAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfRgAlterar)
                        .addGap(248, 248, 248))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addComponent(jtfEnderecoAlterar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel23)
                                    .addComponent(jtfNumeroAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel24)
                                    .addComponent(jtfComplementoAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtfDataAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addComponent(jtfCidadeAlterar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel28)
                                    .addComponent(jcbUfAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jtfCepAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jtfBairroAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jbCancelarAlterar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jbAlterar))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel35)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtfPesquisa)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbPesquisa))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jtfMatriculaAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtfNomeAlterar))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel30)
                                            .addComponent(jtfTelefoneAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel31)
                                            .addComponent(jtfCelularAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jtfCursoAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel33))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jlCargaHorariaAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jLabel22)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(97, 97, 97)
                                        .addComponent(jLabel10))
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(jlCliente1)
                                        .addGap(157, 157, 157)
                                        .addComponent(jLabel20))
                                    .addComponent(jLabel27))
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jtfEmailAlterar)
                                            .addGroup(jPanel5Layout.createSequentialGroup()
                                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel32)
                                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                            .addComponent(jLabel38, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                                                            .addComponent(jtfDataMatriculaAlterar))
                                                        .addGap(18, 18, 18)
                                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(jcbStatus, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(jLabel26, javax.swing.GroupLayout.Alignment.TRAILING))))
                                                .addGap(0, 0, Short.MAX_VALUE))))
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addGap(81, 81, 81)
                                        .addComponent(jLabel21)
                                        .addGap(0, 0, Short.MAX_VALUE)))))
                        .addContainerGap())))
            .addComponent(jSeparator1)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel35)
                    .addComponent(jtfPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbPesquisa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfMatriculaAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfNomeAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlCliente1)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel20)
                        .addComponent(jLabel21)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtfDataAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jtfCpfAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jtfRgAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(jLabel23)
                    .addComponent(jLabel24))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfEnderecoAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfComplementoAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfNumeroAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(jLabel29))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfBairroAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfCepAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(jLabel28))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jcbUfAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfCidadeAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(jLabel31)
                    .addComponent(jLabel32))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfTelefoneAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfCelularAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfEmailAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel33)
                                .addComponent(jLabel26))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jcbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jtfCursoAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addComponent(jLabel34)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jlCargaHorariaAlterar)
                            .addGap(2, 2, 2)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel38)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfDataMatriculaAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbCancelarAlterar)
                    .addComponent(jbAlterar))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("ALTERAR ALUNO", jPanel2);

        jPanel6.setBackground(new java.awt.Color(28, 89, 124));

        jtAlunos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Matricula", "Nome", "Curso", "Data Matricula", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtAlunos.getTableHeader().setReorderingAllowed(false);
        jtAlunos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtAlunosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtAlunos);
        if (jtAlunos.getColumnModel().getColumnCount() > 0) {
            jtAlunos.getColumnModel().getColumn(0).setResizable(false);
            jtAlunos.getColumnModel().getColumn(0).setPreferredWidth(10);
            jtAlunos.getColumnModel().getColumn(3).setResizable(false);
            jtAlunos.getColumnModel().getColumn(3).setPreferredWidth(15);
            jtAlunos.getColumnModel().getColumn(4).setResizable(false);
            jtAlunos.getColumnModel().getColumn(4).setPreferredWidth(30);
        }

        jLabel36.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(255, 255, 255));
        jLabel36.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel36.setText("ALUNOS  CADASTRADOS  NO SISTEMA ");

        jLabel37.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(255, 255, 255));
        jLabel37.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel37.setText("Clique duas vezes no nome do aluno para visualizar os dados dele na tela de alteração.");

        jbAtualizarTabela.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/controlecci/image/actions/atualizar.png"))); // NOI18N
        jbAtualizarTabela.setText("ATUALIZAR TABELA");
        jbAtualizarTabela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAtualizarTabelaActionPerformed(evt);
            }
        });

        jLabel39.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(255, 255, 255));
        jLabel39.setText("QUANTIDADE TOTAL DE ALUNOS:");

        jlQtde.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jlQtde.setForeground(new java.awt.Color(255, 255, 255));
        jlQtde.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlQtde.setText("QTDE");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel36, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
            .addComponent(jLabel37, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel39)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlQtde, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbAtualizarTabela)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel36)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbAtualizarTabela, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel39)
                    .addComponent(jlQtde))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 416, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("VISUALIZAR ALUNOS CADASTRADOS", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalvarActionPerformed
        salvarAluno();
    }//GEN-LAST:event_jbSalvarActionPerformed

    private void jbCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelarActionPerformed
        limparCamposSalvar();
        habilitaDesabilitaCamposSalvar(false);
    }//GEN-LAST:event_jbCancelarActionPerformed

    private void jbNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNovoActionPerformed
        limparCamposSalvar();
        jtfMatricula.requestFocus();
        habilitaDesabilitaCamposSalvar(true);
    }//GEN-LAST:event_jbNovoActionPerformed

    private void jtfCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfCursoActionPerformed
        jlCargaHoraria.setText(cursoController.retornaCargaHoraria(jtfCurso.getText()) + " HORAS");
    }//GEN-LAST:event_jtfCursoActionPerformed

    private void jtfCursoAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfCursoAlterarActionPerformed
        jlCargaHorariaAlterar.setText(cursoController.retornaCargaHoraria(jtfCursoAlterar.getText()) + " HORAS");
    }//GEN-LAST:event_jtfCursoAlterarActionPerformed

    private void jbCancelarAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelarAlterarActionPerformed
        limparCamposAlterar();
        habilitarCamposAlterar(false);
        jtfPesquisa.requestFocus();
    }//GEN-LAST:event_jbCancelarAlterarActionPerformed

    private void jbAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAlterarActionPerformed
        perguntaObservacoes();
        alterarAluno();
    }//GEN-LAST:event_jbAlterarActionPerformed

    private void jtfPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfPesquisaActionPerformed
        habilitarCamposAlterar(true);
        preencherCamposAlteracao();
    }//GEN-LAST:event_jtfPesquisaActionPerformed

    private void jbPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPesquisaActionPerformed
        habilitarCamposAlterar(true);
        preencherCamposAlteracao();
    }//GEN-LAST:event_jbPesquisaActionPerformed

    private void jbAtualizarTabelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAtualizarTabelaActionPerformed
        carregarRegistro();
    }//GEN-LAST:event_jbAtualizarTabelaActionPerformed

    private void jtAlunosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtAlunosMouseClicked
        int linha = jtAlunos.getSelectedRow();
        String aluno = (String) jtAlunos.getValueAt(linha, 1);
        String curso = (String) jtAlunos.getValueAt(linha, 2);
        AlunoModel.nomeAluno = aluno;
        AlunoModel.cursoAluno = curso;

        verificaQuantidadeALuno(aluno);
    }//GEN-LAST:event_jtAlunosMouseClicked

    private void verificaQuantidadeALuno(String pAluno) {
        int x = alunoController.retornaQtdePorAluno(pAluno);
        if (x > 1) {
            SelecionaAluno selecionaAluno = new SelecionaAluno(null, true);
            selecionaAluno.carregarRegistro(pAluno);
            selecionaAluno.setVisible(true);

            ConsultarRegistro consultarRegistro = new ConsultarRegistro();
            JDesktopPane desktopPane = this.getDesktopPane();
            desktopPane.add(consultarRegistro);
            consultarRegistro.carregarRegistroAlunoCurso(AlunoModel.nomeAluno, AlunoModel.cursoAluno);
            consultarRegistro.setVisible(true);
            consultarRegistro.infoAlunoCurso(AlunoModel.nomeAluno, AlunoModel.cursoAluno);
            consultarRegistro.exibirDadosAlunoCurso();
            consultarRegistro.setPosicao();
        } else {
            int dialogResult = JOptionPane.showConfirmDialog(this, " Deseja ver os dados de\n " + AlunoModel.nomeAluno + " ?\n Clique em Yes para confirmar!", "Atenção", JOptionPane.YES_NO_OPTION);
            if (dialogResult == 0) {
                exibirDadosAluno();
            }
        }
    }

    private void perguntaObservacoes() {
        String opcao = JOptionPane.showInputDialog(this, "O aluno possui alguma pendência?\n 1. Sim\n 2. Não", "2");
        if (opcao.equals("1")) {
            String pendencia = JOptionPane.showInputDialog(this, "Insira a pendência do aluno!");
            alunoModel.setPendencia(pendencia);
            salvarAluno();
        } else {
            alunoModel.setPendencia("SEM PENDÊNCIAS");
        }
    }

    private void autoCompletarCurso() {
        ac = new TextAutoCompleter(jtfCurso);
        ac2 = new TextAutoCompleter(jtfCursoAlterar);
        lista = cursoController.getCursoApenas();
        ac.setItems(lista);
        ac2.setItems(lista);
        jlCargaHoraria.setText(cursoController.retornaCargaHoraria(jtfCurso.getText()));
        jlCargaHorariaAlterar.setText(cursoController.retornaCargaHoraria(jtfCursoAlterar.getText()));
    }

    private void autoCompletarAluno() {
        ac = new TextAutoCompleter(jtfPesquisa);
        lista = alunoController.retornaAlunos();
        ac.setItems(lista);
    }

    private void habilitaDesabilitaCamposSalvar(boolean condicao) {
        jtfBairro.setEnabled(condicao);
        jtfCep.setEnabled(condicao);
        jtfCelular.setEnabled(condicao);
        jtfCidade.setEnabled(condicao);
        jtfComplemento.setEnabled(condicao);
        jtfCpf.setEnabled(condicao);
        jtfCurso.setEnabled(condicao);
        jtfData.setEnabled(condicao);
        jtfEmail.setEnabled(condicao);
        jtfEndereco.setEnabled(condicao);
        jtfMatricula.setEnabled(condicao);
        jtfNome.setEnabled(condicao);
        jtfRg.setEnabled(condicao);
        jtfTelefone.setEnabled(condicao);
        jtfNumero.setEnabled(condicao);
        jtfDataMatricula.setEnabled(condicao);
    }

    private void habilitarCamposAlterar(boolean condicao) {
        jlCargaHoraria.setText("");
        jtfBairroAlterar.setEnabled(condicao);
        jtfCepAlterar.setEnabled(condicao);
        jtfCelularAlterar.setEnabled(condicao);
        jtfCidadeAlterar.setEnabled(condicao);
        jtfComplementoAlterar.setEnabled(condicao);
        jtfCpfAlterar.setEnabled(condicao);
        jtfCursoAlterar.setEnabled(condicao);
        jtfDataAlterar.setEnabled(condicao);
        jtfEmailAlterar.setEnabled(condicao);
        jtfEnderecoAlterar.setEnabled(condicao);
        jtfMatriculaAlterar.setEnabled(condicao);
        jtfNomeAlterar.setEnabled(condicao);
        jtfRgAlterar.setEnabled(condicao);
        jtfTelefoneAlterar.setEnabled(condicao);
        jtfNumeroAlterar.setEnabled(condicao);
        jtfDataMatriculaAlterar.setEnabled(condicao);
        /**/
        jtfBairroAlterar.setEditable(condicao);
        jtfCepAlterar.setEditable(condicao);
        jtfCelularAlterar.setEditable(condicao);
        jtfCidadeAlterar.setEditable(condicao);
        jtfComplementoAlterar.setEditable(condicao);
        jtfCpfAlterar.setEditable(condicao);
        jtfCursoAlterar.setEditable(condicao);
        jtfEmailAlterar.setEditable(condicao);
        jtfDataAlterar.setEditable(condicao);
        jtfEnderecoAlterar.setEditable(condicao);
        jtfMatriculaAlterar.setEditable(condicao);
        jtfNomeAlterar.setEditable(condicao);
        jtfRgAlterar.setEditable(condicao);
        jtfTelefoneAlterar.setEditable(condicao);
        jtfNumeroAlterar.setEditable(condicao);
        jtfDataMatriculaAlterar.setEditable(condicao);
    }

    private void limparCamposSalvar() {
        jtfBairro.setText("");
        jtfCep.setText("");
        jtfCelular.setText("");
        jtfCidade.setText("");
        jtfComplemento.setText("");
        jtfCpf.setText("");
        jtfCurso.setText("");
        jtfData.setText("");
        jtfDataMatricula.setText("");
        jtfEmail.setText("");
        jtfEndereco.setText("");
        jtfMatricula.setText("");
        jtfNome.setText("");
        jtfRg.setText("");
        jtfTelefone.setText("");
        jlCargaHoraria.setText("");
    }

    private void limparCamposAlterar() {
        jtfBairroAlterar.setText("");
        jlCargaHorariaAlterar.setText("");
        jtfCepAlterar.setText("");
        jtfCelularAlterar.setText("");
        jtfCidadeAlterar.setText("");
        jtfComplementoAlterar.setText("");
        jtfCpfAlterar.setText("");
        jtfCursoAlterar.setText("");
        jtfDataAlterar.setText("");
        jtfEmailAlterar.setText("");
        jtfEnderecoAlterar.setText("");
        jtfMatriculaAlterar.setText("");
        jtfNomeAlterar.setText("");
        jtfRgAlterar.setText("");
        jtfTelefoneAlterar.setText("");
        jtfPesquisa.setText("");
        jtfNumeroAlterar.setText("");
        jtfDataMatriculaAlterar.setText("");
    }

    public void chamarJDialog() {
        telaCarregamento.fechar();
        telaCarregamento.setVisible(true);
    }

    private void preencherCamposAlteracao() {
        alunoModel = alunoController.getAlunoDao(jtfPesquisa.getText());
        chamarJDialog();

        jtfBairroAlterar.setText(alunoModel.getBairro());
        jtfCepAlterar.setText(alunoModel.getCep());
        jtfCelularAlterar.setText(alunoModel.getCelular());
        jtfCidadeAlterar.setText(alunoModel.getCidade());
        jtfComplementoAlterar.setText(alunoModel.getComplemento());
        jtfCpfAlterar.setText(alunoModel.getCpf());
        jtfCursoAlterar.setText(alunoModel.getCurso());
        jtfDataAlterar.setText(alunoModel.getDataNascimento());
        jtfDataMatriculaAlterar.setText(alunoModel.getDataMatricula());
        jtfEmailAlterar.setText(alunoModel.getEmail());
        jtfEnderecoAlterar.setText(alunoModel.getEndereco());
        jtfMatriculaAlterar.setText(String.valueOf(alunoModel.getMatricula()));
        jtfNomeAlterar.setText(alunoModel.getNome());
        jtfRgAlterar.setText(alunoModel.getRg());
        jtfTelefoneAlterar.setText(alunoModel.getTelefone());
        jtfNumeroAlterar.setText(String.valueOf(alunoModel.getNumero()));
        jlCargaHorariaAlterar.setText(cursoController.retornaCargaHoraria(jtfCursoAlterar.getText()) + " HORAS");
        jcbStatus.setSelectedItem(alunoModel.getSituacao());
    }

    private void salvarAluno() {
        alunoModel = new AlunoModel();

        String opcao = JOptionPane.showInputDialog(this, "O aluno possui alguma pendência?\n 1. Sim\n 2. Não", "2");
        if (opcao.equals("1")) {
            String pendencia = JOptionPane.showInputDialog(this, "Insira a pendência do aluno!");
            alunoModel.setPendencia(pendencia);
            salvarAluno();
        } else {
            alunoModel.setPendencia("SEM PENDÊNCIAS");
        }
        alunoModel.setMatricula(Integer.valueOf(jtfMatricula.getText()));
        alunoModel.setBairro(jtfBairro.getText().toUpperCase());
        alunoModel.setCelular(jtfCelular.getText());
        alunoModel.setCep(jtfCep.getText());
        alunoModel.setCidade(jtfCidade.getText().toUpperCase());
        alunoModel.setCpf(jtfCpf.getText());
        alunoModel.setCurso(jtfCurso.getText().toUpperCase());
        alunoModel.setDataNascimento(jtfData.getText());
        alunoModel.setDataMatricula(jtfDataMatricula.getText());
        alunoModel.setEmail(jtfEmail.getText().toUpperCase());
        alunoModel.setEndereco(jtfEndereco.getText().toUpperCase());
        alunoModel.setNome(jtfNome.getText().toUpperCase());
        alunoModel.setRg(jtfRg.getText());
        alunoModel.setSituacao("ATIVO");
        alunoModel.setUf(jcbUf.getSelectedItem().toString());
        alunoModel.setTelefone(jtfTelefone.getText());
        alunoModel.setNumero(Integer.valueOf(jtfNumero.getText()));

        if (jtfComplemento.getText().equals("")) {
            alunoModel.setComplemento("SEM COMPLEMENTO");
        } else {
            alunoModel.setComplemento(jtfComplemento.getText());
        }
        try {
            if (alunoController.inserirAluno(alunoModel)) {
                mensagemConfirmação.jlMensagem.setText("ALUNO : " + alunoModel.getNome() + " FOI SALVO COM SUCESSO!");
                mensagemConfirmação.jlInfo.setText("NO CURSO: " + alunoModel.getCurso());
                mensagemConfirmação.fechar();
                mensagemConfirmação.setVisible(true);
                LocalUtil.logClass = this.getClass().getName();
                LocalUtil.logType = templateAlerts.mensagemRegistroComum();
                new LogCatUtil().writeFile(String.valueOf(templateAlerts.mensagemSalvar("Aluno " + alunoModel.getNome())));
                limparCamposSalvar();
                menuOpcoes();
            } else {
                JOptionPane.showMessageDialog(null, "Ocorreu um erro ao salvar o aluno: " + alunoModel.getNome(), "Atenção", JOptionPane.WARNING_MESSAGE);
                LocalUtil.logClass = this.getClass().getName();
                LocalUtil.logType = templateAlerts.mensagemRegsitroErro();
                new LogCatUtil().writeFile(String.valueOf(templateAlerts.erroCadastro("Aluno " + alunoModel.getNome())));
            }
        } catch (HeadlessException | ParseException e) {
            LocalUtil.logClass = this.getClass().getName();
            LocalUtil.logType = templateAlerts.mensagemRegsitroErro();
            new LogCatUtil().writeFile(String.valueOf(e));
        }
    }

    private void alterarAluno() {
        alunoModel = new AlunoModel();

        String opcao1 = JOptionPane.showInputDialog(this, "O aluno possui alguma pendência?\n 1. Sim\n 2. Não", "2");
        if (opcao1.equals("1")) {
            String pendencia = JOptionPane.showInputDialog(this, "Insira a pendência do aluno!");
            alunoModel.setPendencia(pendencia);
            salvarAluno();
        } else {
            alunoModel.setPendencia("SEM PENDÊNCIAS");
        }

        alunoModel.setMatricula(Integer.valueOf(jtfMatriculaAlterar.getText()));
        alunoModel.setBairro(jtfBairroAlterar.getText().toUpperCase());
        alunoModel.setCelular(jtfCelularAlterar.getText());
        alunoModel.setCep(jtfCepAlterar.getText());
        alunoModel.setCidade(jtfCidadeAlterar.getText().toUpperCase());
        alunoModel.setCpf(jtfCpfAlterar.getText());
        alunoModel.setCurso(jtfCursoAlterar.getText().toUpperCase());
        alunoModel.setDataNascimento(jtfDataAlterar.getText());
        alunoModel.setDataMatricula(jtfDataMatriculaAlterar.getText());
        alunoModel.setEmail(jtfEmailAlterar.getText().toUpperCase());
        alunoModel.setEndereco(jtfEnderecoAlterar.getText().toUpperCase());
        alunoModel.setNome(jtfNomeAlterar.getText().toUpperCase());
        alunoModel.setRg(jtfRgAlterar.getText());
        alunoModel.setUf(jcbUfAlterar.getSelectedItem().toString());
        alunoModel.setTelefone(jtfTelefoneAlterar.getText());
        alunoModel.setNumero(Integer.valueOf(jtfNumeroAlterar.getText()));
        alunoModel.setSituacao(jcbStatus.getSelectedItem().toString());
        if (jtfComplementoAlterar.getText().equals("")) {
            alunoModel.setComplemento("SEM COMPLEMENTO");
        } else {
            alunoModel.setComplemento(jtfComplementoAlterar.getText());
        }

        if (alunoController.atualizarAluno(alunoModel, jtfPesquisa.getText())) {
            mensagemConfirmação.jlMensagem.setText("ALUNO : " + alunoModel.getNome() + " FOI ATUALIZADO COM SUCESSO!");
            mensagemConfirmação.jlInfo.setText("NO CURSO: " + alunoModel.getCurso());
            mensagemConfirmação.fechar();
            mensagemConfirmação.setVisible(true);

            LocalUtil.logClass = this.getClass().getName();
            LocalUtil.logType = templateAlerts.mensagemRegistroComum();
            new LogCatUtil().writeFile(String.valueOf(templateAlerts.mensagemAlterar("Aluno " + alunoModel.getNome())));

            String opcao = JOptionPane.showInputDialog(this, "Deseja atualizar outro aluno?\n 1. Sim\n 2. Não", "1");
            if (opcao.equals("1")) {
                limparCamposAlterar();
                jtfPesquisa.requestFocus();
            } else {
                limparCamposAlterar();
                habilitarCamposAlterar(false);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Ocorreu um erro ao atualizar o aluno:\n" + alunoModel.getNome(), "Atenção", JOptionPane.WARNING_MESSAGE);
            LocalUtil.logClass = this.getClass().getName();
            LocalUtil.logType = templateAlerts.mensagemRegsitroErro();
            new LogCatUtil().writeFile(String.valueOf(templateAlerts.erroAlterar("Aluno")));
        }
    }

    private void carregarRegistro() {
        colorirLinhas();
        jlQtde.setText(alunoController.retornaQtdeAluno());
        listaAlunoModels = alunoController.getListaAlunoCadastro();
        DefaultTableModel modeloTabela = (DefaultTableModel) jtAlunos.getModel();
        TableColumnModel tcm = jtAlunos.getColumnModel();
        tcm.getColumn(0).setPreferredWidth(2);
        tcm.getColumn(3).setPreferredWidth(2);
        tcm.getColumn(4).setPreferredWidth(5);

        modeloTabela.setNumRows(0);
        try {
            int cont = listaAlunoModels.size();
            for (int i = 0; i < cont; i++) {
                modeloTabela.addRow(new Object[]{
                    listaAlunoModels.get(i).getMatricula(),
                    listaAlunoModels.get(i).getNome(),
                    listaAlunoModels.get(i).getCurso(),
                    listaAlunoModels.get(i).getDataMatricula(),
                    listaAlunoModels.get(i).getSituacao()
                });
            }
            chamarJDialog();
        } catch (Exception e) {
            e.toString();
            LocalUtil.logClass = this.getClass().getName();
            LocalUtil.logType = templateAlerts.mensagemRegsitroErro();
            new LogCatUtil().writeFile(String.valueOf(templateAlerts.erroBuscarDados("Aluno")));
        }
    }

    public void setPosicao() {
        Dimension d = this.getDesktopPane().getSize();
        this.setLocation((d.width - this.getSize().width) / 2, (d.height - this.getSize().height) / 2);
    }

    public void selecionarTipoCliente() throws ParseException {
        String tipo = JOptionPane.showInputDialog(this, "Selecione o tipo de usuário:\n 1. Pessoa Física\n 2. Pessoa Júridica", "1");
        if (tipo.equals("1")) {
            jlCliente.setText("CPF");
            jtfCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } else if (tipo.equals("2")) {
            jlCliente.setText("CNPJ");
            jtfCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###/####-##")));
        } else {
            JOptionPane.showMessageDialog(this, "Tipo de usuário inválido!", "Atenção", JOptionPane.WARNING_MESSAGE);
            LocalUtil.logClass = this.getClass().getName();
            LocalUtil.logType = templateAlerts.mensagemRegsitroErro();
            new LogCatUtil().writeFile(String.valueOf(templateAlerts.erroCodigoInvalido()));
            this.dispose();
        }
    }

    public void menuOpcoes() throws ParseException {
        String opcao = JOptionPane.showInputDialog(this, "Deseja cadastrar outro aluno?\n 1. Sim\n 2. Não", "1");
        if (opcao.equals("1")) {
            limparCamposSalvar();
            selecionarTipoCliente();
        } else {
            limparCamposSalvar();
            //  this.dispose();
        }
    }

    private void colorirLinhas() {
        ColorirLinhaStatus colorirLinhas = new ColorirLinhaStatus(4);
        jtAlunos.getColumnModel().getColumn(4).setCellRenderer(colorirLinhas);
    }

    private void setarEstado() {
        jcbUf.setModel(new javax.swing.DefaultComboBoxModel<>(
                new String[]{"AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB",
                    "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO"}));
        jcbUf.setSelectedItem("PE");
    }

    private void exibirDadosAluno() {
        ConsultarRegistro consultarRegistro = new ConsultarRegistro();
        JDesktopPane desktopPane = this.getDesktopPane();
        desktopPane.add(consultarRegistro);
        consultarRegistro.exibirDadosAluno();
        consultarRegistro.setVisible(true);
        consultarRegistro.setPosicao();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton jbAlterar;
    private javax.swing.JButton jbAtualizarTabela;
    private javax.swing.JButton jbCancelar;
    private javax.swing.JButton jbCancelarAlterar;
    private javax.swing.JButton jbNovo;
    private javax.swing.JButton jbPesquisa;
    private javax.swing.JButton jbSalvar;
    private javax.swing.JComboBox<String> jcbStatus;
    private javax.swing.JComboBox<String> jcbUf;
    private javax.swing.JComboBox<String> jcbUfAlterar;
    private javax.swing.JLabel jlCargaHoraria;
    private javax.swing.JLabel jlCargaHorariaAlterar;
    private javax.swing.JLabel jlCliente;
    private javax.swing.JLabel jlCliente1;
    private javax.swing.JLabel jlQtde;
    private javax.swing.JTable jtAlunos;
    private javax.swing.JTextField jtfBairro;
    private javax.swing.JTextField jtfBairroAlterar;
    private javax.swing.JFormattedTextField jtfCelular;
    private javax.swing.JFormattedTextField jtfCelularAlterar;
    private javax.swing.JFormattedTextField jtfCep;
    private javax.swing.JFormattedTextField jtfCepAlterar;
    private javax.swing.JTextField jtfCidade;
    private javax.swing.JTextField jtfCidadeAlterar;
    private javax.swing.JTextField jtfComplemento;
    private javax.swing.JTextField jtfComplementoAlterar;
    private javax.swing.JFormattedTextField jtfCpf;
    private javax.swing.JFormattedTextField jtfCpfAlterar;
    private javax.swing.JTextField jtfCurso;
    private javax.swing.JTextField jtfCursoAlterar;
    private javax.swing.JFormattedTextField jtfData;
    private javax.swing.JTextField jtfDataAlterar;
    private javax.swing.JFormattedTextField jtfDataMatricula;
    private javax.swing.JFormattedTextField jtfDataMatriculaAlterar;
    private javax.swing.JTextField jtfEmail;
    private javax.swing.JTextField jtfEmailAlterar;
    private javax.swing.JTextField jtfEndereco;
    private javax.swing.JTextField jtfEnderecoAlterar;
    private javax.swing.JTextField jtfMatricula;
    private javax.swing.JTextField jtfMatriculaAlterar;
    private javax.swing.JTextField jtfNome;
    private javax.swing.JTextField jtfNomeAlterar;
    private javax.swing.JTextField jtfNumero;
    private javax.swing.JTextField jtfNumeroAlterar;
    private javax.swing.JTextField jtfPesquisa;
    private javax.swing.JTextField jtfRg;
    private javax.swing.JTextField jtfRgAlterar;
    private javax.swing.JFormattedTextField jtfTelefone;
    private javax.swing.JFormattedTextField jtfTelefoneAlterar;
    // End of variables declaration//GEN-END:variables
}
