package com.controlecci.view.SCCI;

import com.controlecci.controller.CursoController;
import com.controlecci.model.CursoModel;
import com.controlecci.util.LocalUtil;
import com.controlecci.util.LogCatUtil;
import com.controlecci.util.MascarasUtil;
import com.controlecci.util.TemplateAlerts;
import com.controlecci.view.utils.MensagemConfirmação;
import com.controlecci.view.utils.TelaCarregamento;
import com.mxrck.autocompleter.AutoCompleter;
import com.mxrck.autocompleter.TextAutoCompleter;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Instrutores
 */
public class AtualizarCurso extends javax.swing.JDialog {
  CursoController cursoController = new CursoController();
    CursoModel cursoModel = new CursoModel();
    MensagemConfirmação mensagemConfirmação = new MensagemConfirmação(null, true);
    TelaCarregamento telaCarregamento = new TelaCarregamento(null, true);
    ArrayList<CursoModel> listaCursoModels = new ArrayList<>();
    private AutoCompleter ac;
    public ArrayList lista = new ArrayList<>();
    MascarasUtil mascarasUtil = new MascarasUtil();
    TemplateAlerts templateAlerts = new TemplateAlerts();
    /**
     * Creates new form AtualizarCurso
     * @param parent
     * @param modal
     */
    public AtualizarCurso(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jtfPequisa = new javax.swing.JTextField();
        jbPesquisar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jtfCurso = new javax.swing.JTextField();
        jtfModulos = new javax.swing.JTextField();
        jtfValor = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jbAlterar = new javax.swing.JButton();
        jbCancelar = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jtfCargaHoraria = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel5.setBackground(new java.awt.Color(28, 89, 124));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("PESQUISA");

        jtfPequisa.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jtfPequisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfPequisaActionPerformed(evt);
            }
        });

        jbPesquisar.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jbPesquisar.setText("PESQUISAR");
        jbPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPesquisarActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("CURSO");

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("CARGA HORÁRIA");

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("MÓDULOS");

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("VALOR");

        jtfCurso.setEditable(false);
        jtfCurso.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jtfModulos.setEditable(false);
        jtfModulos.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jtfValor.setEditable(false);
        jtfValor.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jbAlterar.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jbAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/controlecci/image/actions/atualizar.png"))); // NOI18N
        jbAlterar.setText("ALTERAR");
        jbAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAlterarActionPerformed(evt);
            }
        });

        jbCancelar.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jbCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/controlecci/image/actions/cancelar.png"))); // NOI18N
        jbCancelar.setText("CANCELAR");
        jbCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelarActionPerformed(evt);
            }
        });

        jtfCargaHoraria.setEditable(false);
        try {
            jtfCargaHoraria.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jtfCargaHoraria.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtfCargaHoraria.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jbCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbAlterar)
                        .addGap(30, 30, 30))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfPequisa, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbPesquisar)
                        .addGap(33, 33, 33))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jtfCargaHoraria, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(95, 95, 95)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jtfValor)))
                            .addComponent(jLabel7)
                            .addComponent(jLabel9)
                            .addComponent(jtfCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 567, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfModulos, javax.swing.GroupLayout.PREFERRED_SIZE, 567, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(28, Short.MAX_VALUE))))
            .addComponent(jSeparator2)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jtfPequisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbPesquisar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfModulos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtfValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfCargaHoraria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel8))
                .addGap(20, 20, 20)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbCancelar)
                    .addComponent(jbAlterar))
                .addContainerGap(83, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 617, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 405, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfPequisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfPequisaActionPerformed
        habilitaDesabilitaCamposAlteracao(true);
        jtfCurso.requestFocus();
        preencherDadosAlteracao();
    }//GEN-LAST:event_jtfPequisaActionPerformed

    private void jbPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPesquisarActionPerformed
        habilitaDesabilitaCamposAlteracao(true);
    }//GEN-LAST:event_jbPesquisarActionPerformed

    private void jbAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAlterarActionPerformed
        habilitaDesabilitaCamposAlteracao(true);
        alterarCurso();
    }//GEN-LAST:event_jbAlterarActionPerformed

    private void jbCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelarActionPerformed
        limparAlteracao();
        habilitaDesabilitaCamposAlteracao(false);
    }//GEN-LAST:event_jbCancelarActionPerformed

//    private void limparCadastro() {
//        jtfCadastroCargaHoraria.setText("");
//        jtfCadastroCurso.setText("");
//        jtfCadastroModulos.setText("");
//        jtfCadastroValor.setText("");
//        jtfCadastroCurso.requestFocus();
//    }

    private void limparAlteracao() {
        jtfCurso.setText("");
        jtfModulos.setText("");
        jtfCargaHoraria.setText("");
        jtfValor.setText("");
        jtfPequisa.setText("");
        jtfPequisa.requestFocus();
    }

//    private void habilitaDesabilitaCamposCadastro(boolean condicao) {
//        jtfCadastroCargaHoraria.setEnabled(condicao);
//        jtfCadastroCurso.setEnabled(condicao);
//        jtfCadastroModulos.setEnabled(condicao);
//        jtfCadastroValor.setEnabled(condicao);
//    }

    private void habilitaDesabilitaCamposAlteracao(boolean condicao) {
        jtfCurso.setEnabled(condicao);
        jtfModulos.setEnabled(condicao);
        jtfCargaHoraria.setEnabled(condicao);
        jtfValor.setEnabled(condicao);
        jtfCurso.setEditable(condicao);
        jtfModulos.setEditable(condicao);
        jtfCargaHoraria.setEditable(condicao);
        jtfValor.setEditable(condicao);
    }

    private void preencherDadosAlteracao() {
        try {
            cursoModel = cursoController.getInfoCurso(jtfPequisa.getText());
            jtfCurso.setText(cursoModel.getNomeCurso());
            jtfModulos.setText(cursoModel.getModulos());
            jtfValor.setText(String.valueOf(cursoModel.getValor()));
            jtfCargaHoraria.setText(cursoModel.getCargaHoraria());
        } catch (Exception e) {
            LocalUtil.logClass = this.getClass().getName();
            LocalUtil.logType = templateAlerts.mensagemRegsitroErro();
            new LogCatUtil().writeFile(String.valueOf("Erro ao carregar os dados para preencher\n" + e.toString()));
        }
    }

//    private void salvarCurso() {
//        cursoModel.setNomeCurso(jtfCadastroCurso.getText().toUpperCase());
//        cursoModel.setModulos(jtfCadastroModulos.getText().toUpperCase());
//        cursoModel.setCargaHoraria(jtfCadastroCargaHoraria.getText());
//        cursoModel.setValor(Double.parseDouble(mascarasUtil.converterVirgulaParaPonto(jtfCadastroValor.getText())));
//
//        if (cursoController.salvarCurso(cursoModel)) {
//            mensagemConfirmação.jlMensagem.setText("O CURSO: " + cursoModel.getNomeCurso().toUpperCase() + " FOI SALVO COM SUCESSO!");
//            mensagemConfirmação.jlInfo.setText("MÓDULOS: " + cursoModel.getModulos().toUpperCase());
//            mensagemConfirmação.fechar();
//            mensagemConfirmação.setVisible(true);
//
//            LocalUtil.logClass = this.getClass().getName();
//            LocalUtil.logType = templateAlerts.mensagemRegistroComum();
//            new LogCatUtil().writeFile(String.valueOf("O curso " + cursoModel.getNomeCurso() + " foi salvo com sucesso!"));
//            limparCadastro();
//        } else {
//            JOptionPane.showMessageDialog(null, "Ocorreu um erro ao salvar o curso " + cursoModel.getNomeCurso().toUpperCase(), "Atenção", JOptionPane.WARNING_MESSAGE);
//
//            LocalUtil.logClass = this.getClass().getName();
//            LocalUtil.logType = templateAlerts.mensagemRegsitroErro();
//            new LogCatUtil().writeFile(String.valueOf(templateAlerts.mensagemCadastro("curso")));
//        }
//    }

    private void alterarCurso() {
        // cursoModel = new CursoModel();
        cursoModel.setNomeCurso(jtfCurso.getText().toUpperCase());
        cursoModel.setModulos(jtfModulos.getText().toUpperCase());
        cursoModel.setCargaHoraria(jtfCargaHoraria.getText());
        cursoModel.setValor(Double.parseDouble(mascarasUtil.converterVirgulaParaPonto(jtfValor.getText())));

        if (cursoController.alterarCurso(cursoModel, jtfPequisa.getText())) {
            mensagemConfirmação.jlMensagem.setText("O CURSO: " + cursoModel.getNomeCurso().toUpperCase() + " FOI ALTERADO COM SUCESSO!");
            mensagemConfirmação.jlInfo.setText("MÓDULOS: " + cursoModel.getModulos().toUpperCase());
            mensagemConfirmação.fechar();
            mensagemConfirmação.setVisible(true);

            LocalUtil.logClass = this.getClass().getName();
            LocalUtil.logType = templateAlerts.mensagemRegistroComum();
            new LogCatUtil().writeFile(String.valueOf("O curso " + cursoModel.getNomeCurso() + " foi alterado com sucesso!"));

            limparAlteracao();
            habilitaDesabilitaCamposAlteracao(false);
        } else {
            JOptionPane.showMessageDialog(null, "Ocorreu um erro ao alterar o curso: " + cursoModel.getNomeCurso(), "Atenção", JOptionPane.WARNING_MESSAGE);

            LocalUtil.logClass = this.getClass().getName();
            LocalUtil.logType = templateAlerts.mensagemRegsitroErro();
            new LogCatUtil().writeFile(String.valueOf(templateAlerts.erroAlterar("curso")));
        }
    }

    private void autoCompletar() {
        ac = new TextAutoCompleter(jtfPequisa);
        lista = cursoController.getCursoApenas();
        ac.setItems(lista);
    }

    public void chamarJDialog() {
        telaCarregamento.fechar();
        telaCarregamento.setVisible(true);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JButton jbAlterar;
    private javax.swing.JButton jbCancelar;
    private javax.swing.JButton jbPesquisar;
    private javax.swing.JFormattedTextField jtfCargaHoraria;
    private javax.swing.JTextField jtfCurso;
    private javax.swing.JTextField jtfModulos;
    private javax.swing.JTextField jtfPequisa;
    private javax.swing.JTextField jtfValor;
    // End of variables declaration//GEN-END:variables
}
