package com.controlecci.view.utils;

import com.controlecci.controller.AlunoController;
import com.controlecci.controller.CursoController;
import com.controlecci.model.AlunoModel;
import com.controlecci.util.ColorirLinhaStatus;
import com.controlecci.util.GetDateUtil;
import com.controlecci.util.LocalUtil;
import com.controlecci.util.LogCatUtil;
import com.controlecci.util.TemplateAlerts;
import com.controlecci.view.SCCI.AlunoView;
import com.controlecci.view.SCCI.ConsultarRegistro;
import com.mxrck.autocompleter.AutoCompleter;
import java.util.ArrayList;
import javax.swing.JDesktopPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author joseluiz
 */
public class SelecionaAluno extends javax.swing.JDialog {

    AlunoModel alunoModel = new AlunoModel();
    AlunoController alunoController = new AlunoController();
    CursoController cursoController = new CursoController();
    public ArrayList lista = new ArrayList<>();
    public ArrayList<AlunoModel> listaAlunoModels = new ArrayList<>();

    MensagemConfirmação mensagemConfirmação = new MensagemConfirmação(null, true);
    TelaCarregamento telaCarregamento = new TelaCarregamento(null, true);
    AlunoView alunoView = new AlunoView();

    GetDateUtil getDateUtil = new GetDateUtil();
    TemplateAlerts templateAlerts = new TemplateAlerts();

    private AutoCompleter ac, ac2;

    /**
     * Creates new form SelecionaALuno
     *
     * @param parent
     * @param modal
     */
    public SelecionaAluno(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtAlunos = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jlAluno = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("SELEÇÃO DE FICHA");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setToolTipText("");

        jtAlunos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Matrícula", "Curso", "Situação"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtAlunos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtAlunosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtAlunos);
        if (jtAlunos.getColumnModel().getColumnCount() > 0) {
            jtAlunos.getColumnModel().getColumn(0).setResizable(false);
            jtAlunos.getColumnModel().getColumn(0).setPreferredWidth(10);
            jtAlunos.getColumnModel().getColumn(1).setPreferredWidth(80);
            jtAlunos.getColumnModel().getColumn(2).setResizable(false);
            jtAlunos.getColumnModel().getColumn(2).setPreferredWidth(10);
        }

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ESTE ALUNO POSSUI MAIS DE UMA FICHA DE CADASTRO");

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("SELECIONE QUAL CURSO DELE VOCÊ DESEJA VISUALIZAR OS DADOS");

        jlAluno.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        jlAluno.setForeground(new java.awt.Color(4, 60, 87));
        jlAluno.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlAluno.setText("NOME DO ALUNO");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel3.setText("VOLTAR");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jlAluno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 674, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel3)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlAluno)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        this.dispose();
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jtAlunosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtAlunosMouseClicked
        carregarDados();
    }//GEN-LAST:event_jtAlunosMouseClicked

    private void colorirLinhas() {
        ColorirLinhaStatus colorirLinhas = new ColorirLinhaStatus(2);
        jtAlunos.getColumnModel().getColumn(2).setCellRenderer(colorirLinhas);
    }

    public void carregarRegistro(String pAluno) {
        colorirLinhas();
        jlAluno.setText(pAluno);
        listaAlunoModels = alunoController.getListaPorAluno(pAluno);
        DefaultTableModel modeloTabela = (DefaultTableModel) jtAlunos.getModel();
        modeloTabela.setNumRows(0);
        try {
            int cont = listaAlunoModels.size();
            for (int i = 0; i < cont; i++) {
                modeloTabela.addRow(new Object[]{
                    listaAlunoModels.get(i).getMatricula(),
                    //        listaAlunoModels.get(i).getNome(),
                    listaAlunoModels.get(i).getCurso(),
                    listaAlunoModels.get(i).getSituacao()
                });
            }
            //     chamarJDialog();
        } catch (Exception e) {
            e.toString();
            LocalUtil.logClass = this.getClass().getName();
            LocalUtil.logType = templateAlerts.mensagemRegsitroErro();
            new LogCatUtil().writeFile(String.valueOf(templateAlerts.erroBuscarDados("Aluno")));
        }
    }

    private void carregarDados() {
        int linha = jtAlunos.getSelectedRow();
        String aluno = jlAluno.getText();
        String curso = (String) jtAlunos.getValueAt(linha, 1);

        ConsultarRegistro consultarRegistro = new ConsultarRegistro();
        JDesktopPane desktopPane = alunoView.getDesktopPane();
        desktopPane.add(consultarRegistro);
        consultarRegistro.exibirDadosAluno();
        consultarRegistro.carregarAlunoRegistro(aluno, curso);
        consultarRegistro.setVisible(true);
        consultarRegistro.setPosicao();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jlAluno;
    private javax.swing.JTable jtAlunos;
    // End of variables declaration//GEN-END:variables
}
